stages:
  load_save:
    cmd: python src/stage_01_load_save.py -c config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data/cat/
      - data/dog/

  
  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py -c config/config.yaml -p params.yaml
    deps:
      - src\stage_02_prepare_base_model.py
      - src\utils\all_utils.py
      - src\utils\models.py
      - config\config.yaml
      - params.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - CLASSES
    outs:
      - artifacts\base_model\updated_VGG16_base_model.h5
      
  prepare_callbacks:
    cmd: python src/stage_03_prepare_callbacks.py -c config/config.yaml -p params.yaml
    deps:
      - src\stage_03_prepare_callbacks.py
      - src\utils\all_utils.py
      - src\utils\callbacks.py
      - params.yaml
      - config\config.yaml
    outs:
      - artifacts\callbacks\tensorboard_cb.cb
      - artifacts\callbacks\checkpoint_cb.cb

  training:
    cmd: python src/stage_04_training.py -c config/config.yaml -p params.yaml
    deps:
      - src\stage_04_training.py
      - src\utils\all_utils.py
      - src\utils\callbacks.py
      - src\utils\models.py
      - src\utils\data_management.py
      - config\config.yaml
      - params.yaml
      - artifacts\base_model\updated_VGG16_base_model.h5     
      - data
      - artifacts\callbacks\tensorboard_cb.cb
      - artifacts\callbacks\checkpoint_cb.cb
    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts/model
    
  evaluate:
    cmd: python src/stage_05_evaluate.py -c config/config.yaml -p params.yaml
    deps:
      - src\stage_05_evaluate.py
      - src\utils\all_utils.py
      - src\utils\models.py
      - config\config.yaml
      - params.yaml
      - artifacts\model
    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts\report_dir\score.json