artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  TRAINED_MODEL_NAME: model_new.h5
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: VGG16_base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_VGG16_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: data
  MODEL_SCORE: score.json
  REPORT_DIR: report_dir

source_download_dirs:
  - ../outside_data/dog
  - ../outside_data/cat

local_data_dirs:
  - data/dog
  - data/cat